### ISSUE TITLE
unicode test fails; comparand not quoted

### ISSUE THREAD

**Issue by Alexir** [spanishdict/fold_to_ascii#4]
it has to be `'unicode'`, not `unicode`

```
$ python 
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fold_to_ascii import fold
>>> string = 'foo'
>>> fold(string)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexr/anaconda3/envs/cobot/lib/python3.7/site-packages/fold_to_ascii/core.py", line 27, in fold
    if type(unicode_string) != unicode:
NameError: name 'unicode' is not defined
>>> type(string) != unicode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'unicode' is not defined
>>> type(string) != 'unicode'
True
>>> 
```

**Comment by sandinmyjoints** [comment]
I think this was due to the last release not being built properly. Try now!
